/**
 * @file bcm_sim.h
 *
 * @brief This header file was generated by cantools version 42.0.3 Tue Jul 21 01:16:45 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef BCM_SIM_H
#define BCM_SIM_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define BCM_SIM_RUN_META_FRAME_ID (0xf0u)
#define BCM_SIM_ENGINE_STATUS_FRAME_ID (0x100u)
#define BCM_SIM_VEHICLE_SPEED_FRAME_ID (0x101u)
#define BCM_SIM_BRAKE_STATUS_FRAME_ID (0x102u)
#define BCM_SIM_POWERTRAIN_HEALTH_FRAME_ID (0x110u)
#define BCM_SIM_CHASSIS_HEALTH_FRAME_ID (0x111u)
#define BCM_SIM_THROTTLE_SUBSYSTEM_FRAME_ID (0x120u)

/* Frame lengths in bytes. */
#define BCM_SIM_RUN_META_LENGTH (6u)
#define BCM_SIM_ENGINE_STATUS_LENGTH (4u)
#define BCM_SIM_VEHICLE_SPEED_LENGTH (2u)
#define BCM_SIM_BRAKE_STATUS_LENGTH (2u)
#define BCM_SIM_POWERTRAIN_HEALTH_LENGTH (5u)
#define BCM_SIM_CHASSIS_HEALTH_LENGTH (3u)
#define BCM_SIM_THROTTLE_SUBSYSTEM_LENGTH (4u)

/* Extended or standard frame types. */
#define BCM_SIM_RUN_META_IS_EXTENDED (0)
#define BCM_SIM_ENGINE_STATUS_IS_EXTENDED (0)
#define BCM_SIM_VEHICLE_SPEED_IS_EXTENDED (0)
#define BCM_SIM_BRAKE_STATUS_IS_EXTENDED (0)
#define BCM_SIM_POWERTRAIN_HEALTH_IS_EXTENDED (0)
#define BCM_SIM_CHASSIS_HEALTH_IS_EXTENDED (0)
#define BCM_SIM_THROTTLE_SUBSYSTEM_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define BCM_SIM_RUN_META_SCENARIO_ID_NORMAL_CHOICE (0u)
#define BCM_SIM_RUN_META_SCENARIO_ID_BATERIA_PROGRESIVA_CHOICE (1u)
#define BCM_SIM_RUN_META_SCENARIO_ID_BATERIA_SUBITA_CHOICE (2u)
#define BCM_SIM_RUN_META_SCENARIO_ID_TEMPERATURA_PROGRESIVA_CHOICE (3u)
#define BCM_SIM_RUN_META_SCENARIO_ID_TEMPERATURA_RAPIDA_CHOICE (4u)
#define BCM_SIM_RUN_META_SCENARIO_ID_ACEITE_PROGRESIVA_CHOICE (5u)
#define BCM_SIM_RUN_META_SCENARIO_ID_ACEITE_SUBITA_CHOICE (6u)
#define BCM_SIM_RUN_META_SCENARIO_ID_CKP_INTERMITENTE_CHOICE (7u)
#define BCM_SIM_RUN_META_SCENARIO_ID_CKP_PERDIDA_TOTAL_CHOICE (8u)
#define BCM_SIM_RUN_META_SCENARIO_ID_LLANTA_LENTA_CHOICE (9u)
#define BCM_SIM_RUN_META_SCENARIO_ID_LLANTA_ABRUPTA_CHOICE (10u)
#define BCM_SIM_RUN_META_SCENARIO_ID_COMBUSTIBLE_CONSUMO_NORMAL_CHOICE (11u)
#define BCM_SIM_RUN_META_SCENARIO_ID_ACELERADOR_PROGRESIVA_CHOICE (12u)
#define BCM_SIM_RUN_META_SCENARIO_ID_ACELERADOR_SUBITA_CHOICE (13u)

/* Frame Names. */
#define BCM_SIM_RUN_META_NAME "RunMeta"
#define BCM_SIM_ENGINE_STATUS_NAME "EngineStatus"
#define BCM_SIM_VEHICLE_SPEED_NAME "VehicleSpeed"
#define BCM_SIM_BRAKE_STATUS_NAME "BrakeStatus"
#define BCM_SIM_POWERTRAIN_HEALTH_NAME "PowertrainHealth"
#define BCM_SIM_CHASSIS_HEALTH_NAME "ChassisHealth"
#define BCM_SIM_THROTTLE_SUBSYSTEM_NAME "ThrottleSubsystem"

/* Signal Names. */
#define BCM_SIM_RUN_META_SCENARIO_ID_NAME "ScenarioId"
#define BCM_SIM_RUN_META_RUN_ID_NAME "RunId"
#define BCM_SIM_RUN_META_SEED_LOW16_NAME "SeedLow16"
#define BCM_SIM_RUN_META_TIME_S_NAME "TimeS"
#define BCM_SIM_ENGINE_STATUS_RPM_NAME "RPM"
#define BCM_SIM_ENGINE_STATUS_COOLANT_TEMP_NAME "CoolantTemp"
#define BCM_SIM_ENGINE_STATUS_ENGINE_RUNNING_NAME "EngineRunning"
#define BCM_SIM_VEHICLE_SPEED_SPEED_NAME "Speed"
#define BCM_SIM_BRAKE_STATUS_BRAKE_PEDAL_PCT_NAME "BrakePedalPct"
#define BCM_SIM_BRAKE_STATUS_BRAKE_OVERRIDE_FLAG_NAME "BrakeOverrideFlag"
#define BCM_SIM_POWERTRAIN_HEALTH_BATTERY_VOLTAGE_NAME "BatteryVoltage"
#define BCM_SIM_POWERTRAIN_HEALTH_OIL_PRESSURE_NAME "OilPressure"
#define BCM_SIM_POWERTRAIN_HEALTH_CRANK_SIGNAL_QUALITY_NAME "CrankSignalQuality"
#define BCM_SIM_CHASSIS_HEALTH_TIRE_PRESSURE_NAME "TirePressure"
#define BCM_SIM_CHASSIS_HEALTH_FUEL_LEVEL_PCT_NAME "FuelLevelPct"
#define BCM_SIM_THROTTLE_SUBSYSTEM_ACCEL_PEDAL_PCT_NAME "AccelPedalPct"
#define BCM_SIM_THROTTLE_SUBSYSTEM_THROTTLE_POSITION_PCT_NAME "ThrottlePositionPct"
#define BCM_SIM_THROTTLE_SUBSYSTEM_THROTTLE_EXPECTED_PCT_NAME "ThrottleExpectedPct"
#define BCM_SIM_THROTTLE_SUBSYSTEM_THROTTLE_RESIDUAL_PCT_NAME "ThrottleResidualPct"

/**
 * Signals in message RunMeta.
 *
 * Metadata de la corrida sintetica generada en la STM32: escenario, run_id, semilla (16 bits bajos) y tiempo transcurrido. Replica las columnas run_id/escenario/seed/time_s del dataset generado con generador_multidtc.py.
 *
 * All signal values are as on the CAN bus.
 */
struct bcm_sim_run_meta_t {
    /**
     * Range: 0..31 (0..31 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t scenario_id;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t run_id;

    /**
     * Range: 0..65535 (0..65535 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t seed_low16;

    /**
     * Range: 0..600 (0..600 s)
     * Scale: 1
     * Offset: 0
     */
    uint16_t time_s;
};

/**
 * Signals in message EngineStatus.
 *
 * Estado de motor: RPM, temperatura de refrigerante y estado de marcha. Simulado en StartCanTxTask.
 *
 * All signal values are as on the CAN bus.
 */
struct bcm_sim_engine_status_t {
    /**
     * Range: 0..8000 (0..8000 rpm)
     * Scale: 1
     * Offset: 0
     */
    uint16_t rpm;

    /**
     * Range: 0..255 (-40..215 degC)
     * Scale: 1
     * Offset: -40
     */
    uint8_t coolant_temp;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t engine_running;
};

/**
 * Signals in message VehicleSpeed.
 *
 * Velocidad de vehiculo (ABS/ESP). Simulada en StartVehicleTxTask.
 *
 * All signal values are as on the CAN bus.
 */
struct bcm_sim_vehicle_speed_t {
    /**
     * Range: 0..5000 (0..500 km/h)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t speed;
};

/**
 * Signals in message BrakeStatus.
 *
 * Estado de freno: % de pedal + flag de brake-override (capa de seguridad determinista, no-ML). Redefinido v2 -- antes llevaba presion en bar.
 *
 * All signal values are as on the CAN bus.
 */
struct bcm_sim_brake_status_t {
    /**
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_pedal_pct;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_override_flag;
};

/**
 * Signals in message PowertrainHealth.
 *
 * Salud del tren motriz: bateria (P0562), presion de aceite (P0520/P0524), calidad de senal de cigueÃ±al (P0335).
 *
 * All signal values are as on the CAN bus.
 */
struct bcm_sim_powertrain_health_t {
    /**
     * Range: 0..2000 (0..20 V)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t battery_voltage;

    /**
     * Range: 0..1000 (0..100 psi)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t oil_pressure;

    /**
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t crank_signal_quality;
};

/**
 * Signals in message ChassisHealth.
 *
 * Salud de chasis: presion de llanta (TPMS) y nivel de combustible.
 *
 * All signal values are as on the CAN bus.
 */
struct bcm_sim_chassis_health_t {
    /**
     * Range: 0..600 (0..60 psi)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t tire_pressure;

    /**
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t fuel_level_pct;
};

/**
 * Signals in message ThrottleSubsystem.
 *
 * Subsistema de acelerador / mariposa: pedal (APP), TPS real, TPS esperado por el gemelo digital, y el residuo que distingue mariposa atorada de un pedal a fondo normal.
 *
 * All signal values are as on the CAN bus.
 */
struct bcm_sim_throttle_subsystem_t {
    /**
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t accel_pedal_pct;

    /**
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t throttle_position_pct;

    /**
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t throttle_expected_pct;

    /**
     * Range: -80..80 (-80..80 %)
     * Scale: 1
     * Offset: 0
     */
    int8_t throttle_residual_pct;
};

/**
 * Pack message RunMeta.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int bcm_sim_run_meta_pack(
    uint8_t *dst_p,
    const struct bcm_sim_run_meta_t *src_p,
    size_t size);

/**
 * Unpack message RunMeta.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int bcm_sim_run_meta_unpack(
    struct bcm_sim_run_meta_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RunMeta.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int bcm_sim_run_meta_init(struct bcm_sim_run_meta_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_run_meta_scenario_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_run_meta_scenario_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_run_meta_scenario_id_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_run_meta_scenario_id_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_run_meta_run_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_run_meta_run_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_run_meta_run_id_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_run_meta_run_id_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bcm_sim_run_meta_seed_low16_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_run_meta_seed_low16_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_run_meta_seed_low16_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_run_meta_seed_low16_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bcm_sim_run_meta_time_s_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_run_meta_time_s_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_run_meta_time_s_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_run_meta_time_s_is_in_phys_range(double value);

/**
 * Pack message EngineStatus.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int bcm_sim_engine_status_pack(
    uint8_t *dst_p,
    const struct bcm_sim_engine_status_t *src_p,
    size_t size);

/**
 * Unpack message EngineStatus.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int bcm_sim_engine_status_unpack(
    struct bcm_sim_engine_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EngineStatus.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int bcm_sim_engine_status_init(struct bcm_sim_engine_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bcm_sim_engine_status_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_engine_status_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_engine_status_rpm_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_engine_status_rpm_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_engine_status_coolant_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_engine_status_coolant_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_engine_status_coolant_temp_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_engine_status_coolant_temp_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_engine_status_engine_running_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_engine_status_engine_running_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_engine_status_engine_running_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_engine_status_engine_running_is_in_phys_range(double value);

/**
 * Pack message VehicleSpeed.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int bcm_sim_vehicle_speed_pack(
    uint8_t *dst_p,
    const struct bcm_sim_vehicle_speed_t *src_p,
    size_t size);

/**
 * Unpack message VehicleSpeed.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int bcm_sim_vehicle_speed_unpack(
    struct bcm_sim_vehicle_speed_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from VehicleSpeed.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int bcm_sim_vehicle_speed_init(struct bcm_sim_vehicle_speed_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bcm_sim_vehicle_speed_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_vehicle_speed_speed_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_vehicle_speed_speed_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_vehicle_speed_speed_is_in_phys_range(double value);

/**
 * Pack message BrakeStatus.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int bcm_sim_brake_status_pack(
    uint8_t *dst_p,
    const struct bcm_sim_brake_status_t *src_p,
    size_t size);

/**
 * Unpack message BrakeStatus.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int bcm_sim_brake_status_unpack(
    struct bcm_sim_brake_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BrakeStatus.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int bcm_sim_brake_status_init(struct bcm_sim_brake_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_brake_status_brake_pedal_pct_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_brake_status_brake_pedal_pct_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_brake_status_brake_pedal_pct_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_brake_status_brake_pedal_pct_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_brake_status_brake_override_flag_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_brake_status_brake_override_flag_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_brake_status_brake_override_flag_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_brake_status_brake_override_flag_is_in_phys_range(double value);

/**
 * Pack message PowertrainHealth.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int bcm_sim_powertrain_health_pack(
    uint8_t *dst_p,
    const struct bcm_sim_powertrain_health_t *src_p,
    size_t size);

/**
 * Unpack message PowertrainHealth.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int bcm_sim_powertrain_health_unpack(
    struct bcm_sim_powertrain_health_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from PowertrainHealth.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int bcm_sim_powertrain_health_init(struct bcm_sim_powertrain_health_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bcm_sim_powertrain_health_battery_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_powertrain_health_battery_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_powertrain_health_battery_voltage_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_powertrain_health_battery_voltage_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bcm_sim_powertrain_health_oil_pressure_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_powertrain_health_oil_pressure_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_powertrain_health_oil_pressure_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_powertrain_health_oil_pressure_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_powertrain_health_crank_signal_quality_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_powertrain_health_crank_signal_quality_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_powertrain_health_crank_signal_quality_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_powertrain_health_crank_signal_quality_is_in_phys_range(double value);

/**
 * Pack message ChassisHealth.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int bcm_sim_chassis_health_pack(
    uint8_t *dst_p,
    const struct bcm_sim_chassis_health_t *src_p,
    size_t size);

/**
 * Unpack message ChassisHealth.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int bcm_sim_chassis_health_unpack(
    struct bcm_sim_chassis_health_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ChassisHealth.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int bcm_sim_chassis_health_init(struct bcm_sim_chassis_health_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bcm_sim_chassis_health_tire_pressure_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_chassis_health_tire_pressure_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_chassis_health_tire_pressure_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_chassis_health_tire_pressure_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_chassis_health_fuel_level_pct_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_chassis_health_fuel_level_pct_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_chassis_health_fuel_level_pct_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_chassis_health_fuel_level_pct_is_in_phys_range(double value);

/**
 * Pack message ThrottleSubsystem.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int bcm_sim_throttle_subsystem_pack(
    uint8_t *dst_p,
    const struct bcm_sim_throttle_subsystem_t *src_p,
    size_t size);

/**
 * Unpack message ThrottleSubsystem.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int bcm_sim_throttle_subsystem_unpack(
    struct bcm_sim_throttle_subsystem_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ThrottleSubsystem.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int bcm_sim_throttle_subsystem_init(struct bcm_sim_throttle_subsystem_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_throttle_subsystem_accel_pedal_pct_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_throttle_subsystem_accel_pedal_pct_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_throttle_subsystem_accel_pedal_pct_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_throttle_subsystem_accel_pedal_pct_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_throttle_subsystem_throttle_position_pct_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_throttle_subsystem_throttle_position_pct_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_throttle_subsystem_throttle_position_pct_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_throttle_subsystem_throttle_position_pct_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_throttle_subsystem_throttle_expected_pct_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_throttle_subsystem_throttle_expected_pct_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_throttle_subsystem_throttle_expected_pct_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_throttle_subsystem_throttle_expected_pct_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t bcm_sim_throttle_subsystem_throttle_residual_pct_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_throttle_subsystem_throttle_residual_pct_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_throttle_subsystem_throttle_residual_pct_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_throttle_subsystem_throttle_residual_pct_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
