/**
 * @file bcm_sim.h
 *
 * @brief This header file was generated by cantools version 42.0.3 Tue Jul 21 01:02:24 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef BCM_SIM_H
#define BCM_SIM_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define BCM_SIM_ENGINE_STATUS_FRAME_ID (0x100u)
#define BCM_SIM_VEHICLE_SPEED_FRAME_ID (0x101u)
#define BCM_SIM_BRAKE_STATUS_FRAME_ID (0x102u)

/* Frame lengths in bytes. */
#define BCM_SIM_ENGINE_STATUS_LENGTH (4u)
#define BCM_SIM_VEHICLE_SPEED_LENGTH (2u)
#define BCM_SIM_BRAKE_STATUS_LENGTH (3u)

/* Extended or standard frame types. */
#define BCM_SIM_ENGINE_STATUS_IS_EXTENDED (0)
#define BCM_SIM_VEHICLE_SPEED_IS_EXTENDED (0)
#define BCM_SIM_BRAKE_STATUS_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define BCM_SIM_ENGINE_STATUS_NAME "EngineStatus"
#define BCM_SIM_VEHICLE_SPEED_NAME "VehicleSpeed"
#define BCM_SIM_BRAKE_STATUS_NAME "BrakeStatus"

/* Signal Names. */
#define BCM_SIM_ENGINE_STATUS_RPM_NAME "RPM"
#define BCM_SIM_ENGINE_STATUS_COOLANT_TEMP_NAME "CoolantTemp"
#define BCM_SIM_ENGINE_STATUS_ENGINE_RUNNING_NAME "EngineRunning"
#define BCM_SIM_VEHICLE_SPEED_SPEED_NAME "Speed"
#define BCM_SIM_BRAKE_STATUS_BRAKE_PEDAL_NAME "BrakePedal"
#define BCM_SIM_BRAKE_STATUS_BRAKE_PRESSURE_NAME "BrakePressure"

/**
 * Signals in message EngineStatus.
 *
 * Estado de motor: RPM, temperatura de refrigerante y estado de marcha. Simulado en StartCanTxTask.
 *
 * All signal values are as on the CAN bus.
 */
struct bcm_sim_engine_status_t {
    /**
     * Range: 0..8000 (0..8000 rpm)
     * Scale: 1
     * Offset: 0
     */
    uint16_t rpm;

    /**
     * Range: 0..255 (-40..215 degC)
     * Scale: 1
     * Offset: -40
     */
    uint8_t coolant_temp;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t engine_running;
};

/**
 * Signals in message VehicleSpeed.
 *
 * Velocidad de vehiculo (ABS/ESP). Simulada en StartVehicleTxTask.
 *
 * All signal values are as on the CAN bus.
 */
struct bcm_sim_vehicle_speed_t {
    /**
     * Range: 0..5000 (0..500 km/h)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t speed;
};

/**
 * Signals in message BrakeStatus.
 *
 * Estado de freno: pedal presionado + presion de linea. Simulada en StartVehicleTxTask.
 *
 * All signal values are as on the CAN bus.
 */
struct bcm_sim_brake_status_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_pedal;

    /**
     * Range: 0..500 (0..500 bar)
     * Scale: 1
     * Offset: 0
     */
    uint16_t brake_pressure;
};

/**
 * Pack message EngineStatus.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int bcm_sim_engine_status_pack(
    uint8_t *dst_p,
    const struct bcm_sim_engine_status_t *src_p,
    size_t size);

/**
 * Unpack message EngineStatus.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int bcm_sim_engine_status_unpack(
    struct bcm_sim_engine_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EngineStatus.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int bcm_sim_engine_status_init(struct bcm_sim_engine_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bcm_sim_engine_status_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_engine_status_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_engine_status_rpm_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_engine_status_rpm_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_engine_status_coolant_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_engine_status_coolant_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_engine_status_coolant_temp_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_engine_status_coolant_temp_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_engine_status_engine_running_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_engine_status_engine_running_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_engine_status_engine_running_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_engine_status_engine_running_is_in_phys_range(double value);

/**
 * Pack message VehicleSpeed.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int bcm_sim_vehicle_speed_pack(
    uint8_t *dst_p,
    const struct bcm_sim_vehicle_speed_t *src_p,
    size_t size);

/**
 * Unpack message VehicleSpeed.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int bcm_sim_vehicle_speed_unpack(
    struct bcm_sim_vehicle_speed_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from VehicleSpeed.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int bcm_sim_vehicle_speed_init(struct bcm_sim_vehicle_speed_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bcm_sim_vehicle_speed_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_vehicle_speed_speed_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_vehicle_speed_speed_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_vehicle_speed_speed_is_in_phys_range(double value);

/**
 * Pack message BrakeStatus.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int bcm_sim_brake_status_pack(
    uint8_t *dst_p,
    const struct bcm_sim_brake_status_t *src_p,
    size_t size);

/**
 * Unpack message BrakeStatus.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int bcm_sim_brake_status_unpack(
    struct bcm_sim_brake_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BrakeStatus.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int bcm_sim_brake_status_init(struct bcm_sim_brake_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t bcm_sim_brake_status_brake_pedal_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_brake_status_brake_pedal_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_brake_status_brake_pedal_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_brake_status_brake_pedal_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t bcm_sim_brake_status_brake_pressure_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double bcm_sim_brake_status_brake_pressure_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_brake_status_brake_pressure_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool bcm_sim_brake_status_brake_pressure_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
